### PR TITLE
Update deployments.yaml to allow multiple env-vars.

### PR DESCRIPTION
**Pull request by Technobeats**
Make it possible to set multiple environment variables on deployments e.g. client-secret and client-id.

This makes it easier to populate these via SOPS and avoid clear text secret/values in values.yaml

### CODE REVIEW

**Comment by halkeye** [comment]
I'm cool with the extra env vars. It actually makes sense, but:

1) you doubled up env: so it won't work as yaml
2) Some random values are set for oauth token ids
3) I use sops + helm secrets, so i'm not sure how your change improves that at all
4) can you make sure to update charts.yaml's app version as well?

**Comment by Technobeats** [comment]
Hi, I have updated the PR.

3/ I thought secretKeyRef could only be used on environment variables?

**Comment by halkeye** [comment]
okay I think I see what your trying to get at. As it stands right now, this PR would break mine, and many other people installs .

Lemme chat with @bnfinet to see what our options are. I think at some point vouch added support for everything being env variables. If thats the case, we might be able to have

VOUCH_PORT
env from secrets
env from custom secrets

and it get merged. I'll take a look.

Failing that. Would being able to provide a custom secret for the config work for you?

**Comment by Technobeats** [comment]
Hi Halkeye, indeed my PR will break other deployments and is not backwards compatible.

I found an example config in the vouch-repo with all available environment variables.
https://github.com/vouch/vouch-proxy/blob/master/config/config.yml_example

Maybe I can remove `OAUTH_CLIENT_ID` and `OAUTH_CLIENT_SECRET` so its optional.
This was end user can choose to set via env-vars or plain text in the values.yaml?

extraEnvs:
  - VOUCH_PORT: 9090
  - OAUTH_CLIENT_ID: abc123
  - OAUTH_CLIENT_SECRET: abc123

**Comment by Technobeats** [comment]
Ah yes I see for me thats works :) Thanks I think we can close this PR?

**Pull request closed without merging**
